---
  title: "MAC Field Metadata"
author: "David LeBauer"
date: "June 17, 2016"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sites

## Site names

```{r}
library(googlesheets)
(my_sheets <- gs_ls())
metadata_gs <- googlesheets::gs_url("https://docs.google.com/spreadsheets/d/1s-kQc3K0h4-hfwMzKOU_zpRXN5loByIpKW8Rvw76mh0")

sites <- gs_read(metadata_gs, 'sites') %>% 
  select(sitename)

sitenames <- with(sites, c(sitename, paste0(sitename, " E"), paste0(sitename, " W")))

insert <-  paste0("insert into sites  (sitename, created_at, updated_at) values('", sitenames, "', now(), now());")

writeLines(insert, 'sites.sql')
```

```sh
psql -d bety < sites.sql
```

Link sites to citations

```sh
insert into citations_sites (citation_id, site_id, created_at, updated_at) select 6000000001, id, now(), now() from sites where sitename like 'MAC%';

insert into citations_sites (citation_id, site_id, created_at, updated_at) select 6000000002, id, now(), now() from sites where sitename like 'MAC%';
```

## Elevation

```{r cars}
library(data.table)

elevation <- fread("data/MAC-Gantry_foundation-lines_elevation-survey_9-15-2015.csv",
                   skip = 4, header = FALSE, drop = c(1:6, 9:10, 12:14), 
                   col.names = c("latitude", "longitude", "elevation"))
elevation <- elevation[!is.na(latitude) | !is.na(longitude)]
library(ggplot2)
ggplot(data = elevation) +
  geom_point(aes(longitude, latitude, color = elevation))

boundingbox <- rbind(elevation[longitude > -111.975][latitude == max(latitude)],
                     elevation[longitude > -111.975][latitude == min(latitude)],
                     elevation[longitude < -111.975][latitude == min(latitude)],
                     elevation[longitude < -111.975][latitude == max(latitude)],
                     elevation[longitude > -111.975][latitude == max(latitude)])

write.csv(boundingbox, "/tmp/macboundingbox.csv", row.names = FALSE)

```

## Plot Layout


```{r pressure, echo=FALSE}
# plot_boxes <- function(x_origin = 0, y_origin = 0,
#                        length = 3.5,
#                        alley = 0.5,
#                        row_spacing = 30, 
#                        ranges = 54, 
#                        columns = 16){

require(udunits2)
library(dplyr)
library(ggplot2)

x_origin = 0 
y_origin = 0
length = 3.5
alley = 0.5
row_spacing = 30
ranges = 54
columns = 16

row_spacing_cm <- ud.convert(row_spacing, 'in', 'm')

dx <- 2 * row_spacing_cm
dy <- length

x <- x_origin + (1:columns - 1) * dx
y <- y_origin + (1:ranges - 1) * (length + alley) 

grid <- data.frame(expand.grid(x,y)) %>% 
  transmute(plot = 1:(ranges*columns), x1 = Var1, y1 = Var2, x2 = x1 + dx, y2 = y1 + dy) %>% 
  tidyr::gather(key = 'lat', )


theme_set(theme_bw())
ggplot(data = grid) + 
  geom_text(aes(x1+dx/2, y1+dy/2, label = plot), size = 2) +
  geom_point(aes(x1,y1), size = 1, alpha = 0.4) + 
  geom_point(aes(x2,y2), col = 'red', size = 1, alpha = 0.4) +
  ggtitle('gantry plot layout') + xlab('x') + ylab('y')


grid2 <- grid %>% gather(key, value = x, starts_with("x")) %>% gather(key2, value = y, starts_with("y"))   %>% select(-starts_with("key"))  %>% arrange(plot) %>% setDT

library(spatstat)
plots <- grid2[,polygon(as.data.frame(spatstat::bounding.box.xy(x, y))),by=plot]

```


## Cultivars

```{r cultivars}
bety <- src_postgres(dbname = 'bety', host = 'localhost', user = 'bety', password = 'bety')

cultivars <- tbl(bety, 'cultivars')

specie_id <- tbl(bety, 'species') %>% filter(scientificname == 'Sorghum bicolor') %>% select(id)

library(googlesheets)
accessions_gs <- googlesheets::gs_url("https://docs.google.com/spreadsheets/d/1Nfabx_n1rNlO6NW3olD8MAibJ3KHnOMmMwOYYw4wwGc")
accessions <- googlesheets::gs_read(accessions_gs, 'Accessions')

#accessions <- read.csv("~/Downloads/accessions.csv")

sorghum_cultivars <- accessions %>% 
  transmute(specie_id = 2588, name = Source)

insert <- sorghum_cultivars %>% 
  mutate(insert = paste('insert into cultivars values (specie_id, name, created_at, updated_at) values(', 
                        specie_id, ",", name, ", now(), now());")) %>% 
  select(insert)

writeLines(insert$insert, 'sorghum_cultivars.sql')
```

then insert cultivars (on bety6 / terraref.ncsa.illinois.edu/bety) using

```sh
psql -d bety < sorghum_cultivars.sql
```

## Covariates

For any traits that we upload, an entry in `trait_covariate_associations` is required. By default, they can all have stand age

```{r}
insert_tca <- paste0("insert into trait_covariate_associations (trait_variable_id, covariate_variable_id, required) values (", 6000000001:6000000008, ", 343, 'f');")
writeLines(insert_tca, con = 'trait_covariate_associations.sql')
```